FROM python:3.8-slim


RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get -y --no-install-recommends install build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /arbie

RUN pip install Arbie
